services:
  - type: web
    name: safeweb
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SAFEWEB_ALLOWED_ORIGIN
        value: "https://jerryishere.github.io"
